// packages/publish/cloudflare-pages.ts — Cloudflare Pages deploy adapter.
// Ensures the Pages project exists, then uploads files via the multipart deploy API.
// Reuses bundleProject() from the API; no bundling logic is duplicated here.

import type { DeployResult, PublishAdapter } from './types';

const CF_API = 'https://api.cloudflare.com/client/v4';

// ── Helpers ───────────────────────────────────────────────────────────────────

/** Fetch JSON from Cloudflare API with auth header. Throws on non-2xx. */
async function cfFetch<T = unknown>(
  path: string,
  token: string,
  init: RequestInit = {},
): Promise<T> {
  const res = await fetch(`${CF_API}${path}`, {
    ...init,
    headers: {
      Authorization: `Bearer ${token}`,
      ...((init.headers as Record<string, string>) ?? {}),
    },
  });
  const json = (await res.json()) as { success: boolean; result: T; errors?: { message: string }[] };
  if (!res.ok || !json.success) {
    const msg = json.errors?.[0]?.message ?? res.statusText;
    throw new Error(`Cloudflare API error (${res.status}): ${msg}`);
  }
  return json.result;
}

// ── Project provisioning ──────────────────────────────────────────────────────

/**
 * Ensure a Cloudflare Pages project exists for this slug.
 * Creates one if it does not exist yet. Returns the project name.
 */
export async function ensurePagesProject(
  projectSlug: string,
  accountId: string,
  token: string,
): Promise<string> {
  const projectName = projectSlug.toLowerCase().replace(/[^a-z0-9-]/g, '-');

  try {
    // Check if the project already exists
    await cfFetch(`/accounts/${accountId}/pages/projects/${projectName}`, token);
    return projectName; // already exists
  } catch {
    // Does not exist — create it
    await cfFetch<unknown>(`/accounts/${accountId}/pages/projects`, token, {
      method: 'POST',
      headers: { 'Content-Type': 'application/json' },
      body: JSON.stringify({
        name:              projectName,
        production_branch: 'main',
      }),
    });
    return projectName;
  }
}

// ── Deploy ────────────────────────────────────────────────────────────────────

/**
 * Push bundled assets to Cloudflare Pages using the Direct Upload API.
 * Each asset is appended as a separate multipart field named by its path.
 */
export async function deployToCFPages(
  projectSlug: string,
  assets: Map<string, Uint8Array>,
  accountId: string,
  token: string,
): Promise<DeployResult> {
  const t0 = Date.now();

  // Step 1 — ensure the project exists
  const projectName = await ensurePagesProject(projectSlug, accountId, token);

  // Step 2 — build FormData with every asset
  const form = new FormData();
  const manifest: Record<string, string> = {};

  for (const [path, bytes] of assets.entries()) {
    // Cloudflare Pages expects a trailing-slash-free, leading-slash-present path.
    const key = path.startsWith('/') ? path : `/${path}`;
    // Copy into a plain ArrayBuffer so TS is satisfied with BlobPart typing
    const buf  = bytes.buffer.slice(bytes.byteOffset, bytes.byteOffset + bytes.byteLength) as ArrayBuffer;
    const blob = new Blob([buf], { type: mimeFromPath(path) });
    form.append(key, blob, key.slice(1)); // field name without leading /
    manifest[key] = key;
  }

  // Embed the manifest so CF knows which files belong to this deployment
  form.append(
    '/_headers',
    new Blob(['# Auto-generated by AI Builder Workspace\n'], { type: 'text/plain' }),
    '_headers',
  );

  // Step 3 — POST the deployment
  const res = await fetch(
    `${CF_API}/accounts/${accountId}/pages/projects/${projectName}/deployments`,
    {
      method: 'POST',
      headers: { Authorization: `Bearer ${token}` },
      body: form,
    },
  );

  if (!res.ok) {
    const text = await res.text().catch(() => res.statusText);
    throw new Error(`CF Pages deploy failed (${res.status}): ${text.slice(0, 300)}`);
  }

  const json = (await res.json()) as {
    success: boolean;
    result?: { url?: string; id?: string };
    errors?: { message: string }[];
  };

  if (!json.success) {
    const msg = json.errors?.[0]?.message ?? 'Unknown error';
    throw new Error(`CF Pages deploy error: ${msg}`);
  }

  const deployUrl =
    json.result?.url ??
    `https://${projectName}.pages.dev`;

  return {
    url:          deployUrl,
    durationMs:   Date.now() - t0,
    deploymentId: json.result?.id,
  };
}

// ── Adapter implementation ────────────────────────────────────────────────────

export const cloudflarePagesAdapter: PublishAdapter = {
  id: 'cloudflare-pages',

  async deploy(projectSlug, assets, accountId, token): Promise<DeployResult> {
    return deployToCFPages(projectSlug, assets, accountId, token);
  },
};

// ── MIME helper ───────────────────────────────────────────────────────────────

function mimeFromPath(path: string): string {
  const ext = path.split('.').pop()?.toLowerCase() ?? '';
  const map: Record<string, string> = {
    html: 'text/html',
    htm:  'text/html',
    js:   'application/javascript',
    mjs:  'application/javascript',
    css:  'text/css',
    json: 'application/json',
    svg:  'image/svg+xml',
    png:  'image/png',
    jpg:  'image/jpeg',
    jpeg: 'image/jpeg',
    gif:  'image/gif',
    ico:  'image/x-icon',
    webp: 'image/webp',
    woff: 'font/woff',
    woff2: 'font/woff2',
    txt:  'text/plain',
  };
  return map[ext] ?? 'application/octet-stream';
}
