// packages/agent-core/types.ts — shared agent runtime types.
// These are the base types used by the orchestrator, tools, and the frontend.
// All IDs are UUIDs; all timestamps are ISO 8601 strings.

export type AgentRole =
  | 'planner'
  | 'builder'
  | 'runtime'
  | 'visual'
  | 'backend'
  | 'fixer'
  | 'release';

export type RunStatus =
  | 'queued'
  | 'running'
  | 'paused'
  | 'awaiting_approval'
  | 'completed'
  | 'failed'
  | 'killed';

export type StepStatus =
  | 'pending'
  | 'running'
  | 'completed'
  | 'failed'
  | 'skipped';

export type FindingSeverity = 'error' | 'warning' | 'info';

export type VerificationAdapter =
  | 'lint'
  | 'typecheck'
  | 'build'
  | 'unit'
  | 'integration'
  | 'e2e'
  | 'secretScan'
  | 'depVuln'
  | 'migrationSmoke'
  | 'playwrightRuntime'
  | 'screenshotDiff';

// ── Run ───────────────────────────────────────────────────────────────────────

export interface Run {
  id:          string;
  tenantId:    string;
  projectId:   string;
  createdBy:   string;
  goal:        string;
  model:       string;       // e.g. "ollama/llama3" or "minimax/abab6.5s-chat"
  provider:    string;
  status:      RunStatus;
  startedAt:   string | null;
  endedAt:     string | null;
  summary:     string | null;
  memory:      RunMemory;
  budget:      RunBudget;
  stepCount:   number;
}

// ── Step ──────────────────────────────────────────────────────────────────────

export interface Step {
  id:         string;
  runId:      string;
  role:       AgentRole;
  tool:       string;         // tool name e.g. "fs.write"
  inputHash:  string;         // SHA-256 of tool input (never the raw input in this type)
  outputHash: string | null;  // SHA-256 of tool output
  model:      string;
  status:     StepStatus;
  durationMs: number | null;
  costUsd:    number | null;
  findings:   Finding[];
  createdAt:  string;
}

// ── Tool ──────────────────────────────────────────────────────────────────────

export interface ToolDef {
  name:        string;
  description: string;
  inputSchema: Record<string, unknown>;   // JSON Schema
  outputSchema: Record<string, unknown>;  // JSON Schema
  allowedRoles: AgentRole[];
}

export interface ToolCall {
  tool:   string;
  input:  Record<string, unknown>;
}

export interface ToolResult {
  ok:       boolean;
  output:   Record<string, unknown>;
  findingIds?: string[];   // IDs of findings generated by this call
  durationMs: number;
}

// ── Finding ───────────────────────────────────────────────────────────────────

export interface Finding {
  id:         string;          // UUID; referenced by Fixer role tool calls
  runId:      string;
  stepId:     string | null;
  severity:   FindingSeverity;
  source:     string;          // e.g. "lint" | "typecheck" | "playwright"
  file?:      string;
  line?:      number;
  column?:    number;
  message:    string;
  rule?:      string;
  fixable:    boolean;
  fixed:      boolean;
  createdAt:  string;
}

// ── Verification ──────────────────────────────────────────────────────────────

export interface VerificationResult {
  adapter:    VerificationAdapter;
  ok:         boolean;
  durationMs: number;
  summary:    string;
  findings:   Finding[];
  skipped:    boolean;
  skipReason?: string;
}

// ── Run memory ────────────────────────────────────────────────────────────────

export interface RunMemory {
  goal:               string;
  constraints:        string[];
  model:              string;
  provider:           string;
  affectedFiles:      string[];      // file paths the plan identified
  decisions:          Decision[];
  completedSubtasks:  string[];
  remainingSubtasks:  string[];
  knownBugs:          KnownBug[];
  blockers:           Blocker[];
  verification:       VerificationResult[];
  screenshots:        Screenshot[];
  nextActions:        string[];
}

export interface Decision {
  at:     string;   // ISO timestamp
  reason: string;
  choice: string;
}

export interface KnownBug {
  id:        string;
  file?:     string;
  line?:     number;
  message:   string;
  severity:  FindingSeverity;
  fixedAt?:  string;
}

export interface Blocker {
  id:      string;
  reason:  string;
  at:      string;
  resolved: boolean;
}

export interface Screenshot {
  route:      string;
  viewport:   number;
  url:        string;   // Supabase Storage URL
  capturedAt: string;
  diffPct?:   number;
  passed?:    boolean;
}

// ── Budget ────────────────────────────────────────────────────────────────────

export interface RunBudget {
  maxSteps:   number;    // default 50
  maxTimeMs:  number;    // default 30 * 60 * 1000 (30 min)
  maxCostUsd: number;    // default 5.00
  usedSteps:  number;
  usedTimeMs: number;
  usedCostUsd: number;
}

export const DEFAULT_BUDGET: RunBudget = {
  maxSteps:   50,
  maxTimeMs:  30 * 60 * 1000,
  maxCostUsd: 5,
  usedSteps:  0,
  usedTimeMs: 0,
  usedCostUsd: 0,
};

// ── Realtime events ───────────────────────────────────────────────────────────
// These are broadcast on the Supabase Realtime channel `run:{runId}`.

export type RunEvent =
  | { type: 'step_started';   stepId: string; role: AgentRole; tool: string }
  | { type: 'step_completed'; stepId: string; durationMs: number; ok: boolean }
  | { type: 'step_failed';    stepId: string; error: string }
  | { type: 'memory_updated'; memory: Partial<RunMemory> }
  | { type: 'finding';        finding: Finding }
  | { type: 'log';            level: 'info' | 'warn' | 'error'; message: string }
  | { type: 'run_paused';     reason: string }
  | { type: 'run_completed';  summary: string }
  | { type: 'run_failed';     error: string }
  | { type: 'approval_required'; action: string; bundleId: string };
