// apps/api/build.mjs — esbuild bundler for production Railway deployment.
// Bundles the entire API (including workspace packages) into a single dist/server.js.
import { build } from 'esbuild';
import { fileURLToPath } from 'node:url';
import { dirname, resolve } from 'node:path';
import { execSync } from 'node:child_process';

const __dirname = dirname(fileURLToPath(import.meta.url));

// Capture git SHA + ISO timestamp at build time. Inlined into the bundle via
// esbuild's `define`. Surfaced on /healthz so we can verify which commit is
// running in prod without needing log/SSH access. Falls back to 'unknown' if
// git is unavailable (e.g. in a Docker layer that lacks .git/).
let buildSha = 'unknown';
try {
  buildSha = execSync('git rev-parse --short HEAD', { encoding: 'utf8' }).trim();
} catch { /* keep 'unknown' */ }
const buildTime = new Date().toISOString();

await build({
  entryPoints: [resolve(__dirname, 'src/server.ts')],
  outfile: resolve(__dirname, 'dist/server.js'),
  bundle: true,
  platform: 'node',
  target: 'node20',
  define: {
    '__BUILD_SHA__':  JSON.stringify(buildSha),
    '__BUILD_TIME__': JSON.stringify(buildTime),
  },
  // CJS format: avvio/fastify use dynamic require() inside functions which esbuild's
  // ESM output cannot hoist into static imports → crashes with "Dynamic require of
  // node:events is not supported". CJS format has native require() and avoids this.
  format: 'cjs',
  sourcemap: true,
  external: [
    // native addons / binaries that can't be bundled
    'playwright',
    'playwright-core',
    'esbuild',
    'pg-native',
    // Puppeteer + Chromium binary (Creative Suite: PDF rendering)
    'puppeteer-core',
    '@sparticuz/chromium',
    // ffmpeg static binary (Creative Suite: Music Studio)
    '@ffmpeg-installer/ffmpeg',
    'fluent-ffmpeg',
    // Native archive binding (Creative Suite: Music ZIP packaging)
    'archiver',
  ],
  banner: {
    js: [
      '// @abw/api — bundled production build',
      '// Generated by apps/api/build.mjs — do not edit directly.',
    ].join('\n'),
  },
  logLevel: 'info',
});

console.log('✅  API bundle written to dist/server.js');
