// apps/api/build.mjs — esbuild bundler for production Railway deployment.
// Bundles the entire API (including workspace packages) into a single dist/server.js.
import { build } from 'esbuild';
import { fileURLToPath } from 'node:url';
import { dirname, resolve } from 'node:path';

const __dirname = dirname(fileURLToPath(import.meta.url));

await build({
  entryPoints: [resolve(__dirname, 'src/server.ts')],
  outfile: resolve(__dirname, 'dist/server.js'),
  bundle: true,
  platform: 'node',
  target: 'node20',
  format: 'esm',
  sourcemap: true,
  // 'packages: bundle' requires esbuild >=0.22 — omit it; bundle:true already inlines everything
  external: [
    // native addons / binaries that can't be bundled
    // vault.ts now uses Node's built-in crypto (AES-256-GCM) — libsodium-wrappers removed
    'playwright',
    'playwright-core',
    'esbuild',
    'pg-native',
  ],
  define: {
    'import.meta.url': 'import.meta.url',
  },
  banner: {
    js: [
      '// @abw/api — bundled production build',
      '// Generated by apps/api/build.mjs — do not edit directly.',
    ].join('\n'),
  },
  logLevel: 'info',
});

console.log('✅  API bundle written to dist/server.js');
